#!/usr/bin/env python3
"""Render llm-gen-wiki/index.md from plan.yml and meta.yml."""

import sys

from compute_docs import (
    WIKI_DIR,
    PlanError,
    build_documents,
    letter_for,
    parse_plan,
    strip_inline_comment,
    subtopic_slug,
)


META_PATH = WIKI_DIR / "meta.yml"
INDEX_PATH = WIKI_DIR / "index.md"

_TRANSLATIONS = {
    "English": {
        "wiki_suffix": "Wiki",
        "high": "High Priority",
        "medium": "Medium Priority",
        "low": "Low Priority",
        "branch": "Branch",
        "commit": "Commit",
        "generated_at": "Generated",
        "language_label": "Language",
        "source_files": "source files",
        "footer": "Generated by llm-gen-repo-wiki",
    },
    "Japanese": {
        "wiki_suffix": "Wiki",
        "high": "高優先度",
        "medium": "中優先度",
        "low": "低優先度",
        "branch": "ブランチ",
        "commit": "コミット",
        "generated_at": "生成日時",
        "language_label": "言語",
        "source_files": "ソースファイル",
        "footer": "llm-gen-repo-wiki で生成",
    },
    "Simplified Chinese": {
        "wiki_suffix": "Wiki",
        "high": "高优先级",
        "medium": "中优先级",
        "low": "低优先级",
        "branch": "分支",
        "commit": "提交",
        "generated_at": "生成时间",
        "language_label": "语言",
        "source_files": "个源文件",
        "footer": "由 llm-gen-repo-wiki 生成",
    },
    "Traditional Chinese": {
        "wiki_suffix": "Wiki",
        "high": "高優先級",
        "medium": "中優先級",
        "low": "低優先級",
        "branch": "分支",
        "commit": "提交",
        "generated_at": "生成時間",
        "language_label": "語言",
        "source_files": "個來源檔案",
        "footer": "由 llm-gen-repo-wiki 生成",
    },
    "French": {
        "wiki_suffix": "Wiki",
        "high": "Haute Priorité",
        "medium": "Priorité Moyenne",
        "low": "Basse Priorité",
        "branch": "Branche",
        "commit": "Commit",
        "generated_at": "Généré le",
        "language_label": "Langue",
        "source_files": "fichiers source",
        "footer": "Généré par llm-gen-repo-wiki",
    },
    "German": {
        "wiki_suffix": "Wiki",
        "high": "Hohe Priorität",
        "medium": "Mittlere Priorität",
        "low": "Niedrige Priorität",
        "branch": "Branch",
        "commit": "Commit",
        "generated_at": "Generiert am",
        "language_label": "Sprache",
        "source_files": "Quelldateien",
        "footer": "Generiert von llm-gen-repo-wiki",
    },
    "Spanish": {
        "wiki_suffix": "Wiki",
        "high": "Alta Prioridad",
        "medium": "Prioridad Media",
        "low": "Baja Prioridad",
        "branch": "Rama",
        "commit": "Commit",
        "generated_at": "Generado el",
        "language_label": "Idioma",
        "source_files": "archivos fuente",
        "footer": "Generado por llm-gen-repo-wiki",
    },
    "Korean": {
        "wiki_suffix": "위키",
        "high": "높은 우선순위",
        "medium": "중간 우선순위",
        "low": "낮은 우선순위",
        "branch": "브랜치",
        "commit": "커밋",
        "generated_at": "생성 일시",
        "language_label": "언어",
        "source_files": "소스 파일",
        "footer": "llm-gen-repo-wiki로 생성",
    },
    "Portuguese": {
        "wiki_suffix": "Wiki",
        "high": "Alta Prioridade",
        "medium": "Prioridade Média",
        "low": "Baixa Prioridade",
        "branch": "Branch",
        "commit": "Commit",
        "generated_at": "Gerado em",
        "language_label": "Idioma",
        "source_files": "arquivos fonte",
        "footer": "Gerado por llm-gen-repo-wiki",
    },
    "Italian": {
        "wiki_suffix": "Wiki",
        "high": "Alta Priorità",
        "medium": "Priorità Media",
        "low": "Bassa Priorità",
        "branch": "Branch",
        "commit": "Commit",
        "generated_at": "Generato il",
        "language_label": "Lingua",
        "source_files": "file sorgente",
        "footer": "Generato da llm-gen-repo-wiki",
    },
    "Russian": {
        "wiki_suffix": "Вики",
        "high": "Высокий приоритет",
        "medium": "Средний приоритет",
        "low": "Низкий приоритет",
        "branch": "Ветка",
        "commit": "Коммит",
        "generated_at": "Создано",
        "language_label": "Язык",
        "source_files": "исходных файлов",
        "footer": "Создано с помощью llm-gen-repo-wiki",
    },
}

_LANG_ALIASES = {
    "english": "English",
    "japanese": "Japanese",
    "日本語": "Japanese",
    "simplified chinese": "Simplified Chinese",
    "chinese simplified": "Simplified Chinese",
    "简体中文": "Simplified Chinese",
    "chinese": "Simplified Chinese",
    "traditional chinese": "Traditional Chinese",
    "chinese traditional": "Traditional Chinese",
    "繁體中文": "Traditional Chinese",
    "french": "French",
    "français": "French",
    "francais": "French",
    "german": "German",
    "deutsch": "German",
    "spanish": "Spanish",
    "español": "Spanish",
    "espanol": "Spanish",
    "korean": "Korean",
    "한국어": "Korean",
    "portuguese": "Portuguese",
    "português": "Portuguese",
    "portugues": "Portuguese",
    "italian": "Italian",
    "italiano": "Italian",
    "russian": "Russian",
    "русский": "Russian",
}


def _ui(language):
    key = language.strip()
    canonical = _LANG_ALIASES.get(key.lower()) or _LANG_ALIASES.get(key)
    return _TRANSLATIONS.get(canonical, _TRANSLATIONS["English"])


def parse_meta(path=META_PATH):
    if not path.exists():
        raise PlanError(f"Missing required file: {path}")
    meta = {}
    for raw_line in path.read_text().splitlines():
        line = strip_inline_comment(raw_line).strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        meta[key.strip()] = value
    return meta


def topic_href(topic, position):
    return f"{position:02d}-{topic.get('id', '')}.md"


def subtopic_href(subtopic, position, subtopic_index):
    letter = letter_for(subtopic_index)
    return f"{position:02d}{letter}-{subtopic_slug(subtopic.get('id', ''))}.md"


def render_topic(topic, position, ui):
    href = topic_href(topic, position)
    source_count = len(topic.get("relevant_files", []))
    title = topic.get("title", "")
    description = topic.get("description", "")
    lines = [
        f"{position}. **[{title}]({href})** *({source_count} {ui['source_files']})* — {description}"
    ]
    for subtopic_index, subtopic in enumerate(topic.get("subtopics", [])):
        sub_href = subtopic_href(subtopic, position, subtopic_index)
        sub_title = subtopic.get("title", "")
        sub_description = subtopic.get("description", "")
        lines.append(f"   - [{sub_title}]({sub_href}) — {sub_description}")
    return lines


def render_index(plan, meta):
    language = meta.get("language", "English")
    ui = _ui(language)

    grouped = {"high": [], "medium": [], "low": []}
    for position, topic in enumerate(plan.get("topics", []), start=1):
        importance = topic.get("importance", "medium")
        if importance in grouped:
            grouped[importance].append((position, topic))

    lines = [
        f"# {plan.get('repo', '')} {ui['wiki_suffix']}",
        "",
        "| | |",
        "|---|---|",
        f"| **{ui['branch']}** | `{meta.get('branch', '')}` |",
        f"| **{ui['commit']}** | `{meta.get('commit_hash', '')[:12]}` |",
        f"| **{ui['generated_at']}** | {meta.get('generated_at', '')} |",
        f"| **{ui['language_label']}** | {language} |",
        "",
        plan.get("description", ""),
        "",
    ]

    for importance, heading in (
        ("high", ui["high"]),
        ("medium", ui["medium"]),
        ("low", ui["low"]),
    ):
        topics = grouped[importance]
        if not topics:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for position, topic in topics:
            lines.extend(render_topic(topic, position, ui))
            lines.append("")

    lines.extend(["---", f"*{ui['footer']}*", ""])
    return "\n".join(lines)


def main():
    try:
        plan = parse_plan()
        meta = parse_meta()
        build_documents(plan)
        WIKI_DIR.mkdir(exist_ok=True)
        INDEX_PATH.write_text(render_index(plan, meta))
        print(f"Wrote {INDEX_PATH}")
    except PlanError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
