#!/usr/bin/env python3
"""Render llm-gen-wiki/index.md from plan.yml and meta.yml."""

import sys

from compute_docs import (
    WIKI_DIR,
    PlanError,
    build_documents,
    letter_for,
    parse_plan,
    subtopic_slug,
    strip_inline_comment,
)


META_PATH = WIKI_DIR / "meta.yml"
INDEX_PATH = WIKI_DIR / "index.md"


def parse_meta(path=META_PATH):
    meta = {}
    for raw_line in path.read_text().splitlines():
        line = strip_inline_comment(raw_line).strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        meta[key.strip()] = value
    return meta


def topic_href(topic, position):
    return f"{position:02d}-{topic.get('id', '')}.md"


def subtopic_href(subtopic, position, subtopic_index):
    letter = letter_for(subtopic_index)
    return f"{position:02d}{letter}-{subtopic_slug(subtopic.get('id', ''))}.md"


def render_topic(topic, position):
    href = topic_href(topic, position)
    source_count = len(topic.get("relevant_files", []))
    title = topic.get("title", "")
    description = topic.get("description", "")
    lines = [
        f"{position}. **[{title}]({href})** *({source_count} source files)* — {description}"
    ]
    for subtopic_index, subtopic in enumerate(topic.get("subtopics", [])):
        sub_href = subtopic_href(subtopic, position, subtopic_index)
        sub_title = subtopic.get("title", "")
        sub_description = subtopic.get("description", "")
        lines.append(f"   - [{sub_title}]({sub_href}) — {sub_description}")
    return lines


def render_index(plan, meta):
    grouped = {"high": [], "medium": [], "low": []}
    for position, topic in enumerate(plan.get("topics", []), start=1):
        importance = topic.get("importance", "medium")
        if importance in grouped:
            grouped[importance].append((position, topic))

    lines = [
        f"# {plan.get('repo', '')} Wiki",
        "",
        "| | |",
        "|---|---|",
        f"| **Branch** | `{meta.get('branch', '')}` |",
        f"| **Commit** | `{meta.get('commit_hash', '')[:12]}` |",
        f"| **Generated** | {meta.get('generated_at', '')} |",
        f"| **Language** | {meta.get('language', 'English')} |",
        "",
        plan.get("description", ""),
        "",
    ]

    for importance, heading in (
        ("high", "High Priority"),
        ("medium", "Medium Priority"),
        ("low", "Low Priority"),
    ):
        topics = grouped[importance]
        if not topics:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for position, topic in topics:
            lines.extend(render_topic(topic, position))
            lines.append("")

    lines.extend(["---", "*Generated by llm-gen-repo-wiki*", ""])
    return "\n".join(lines)


def main():
    try:
        plan = parse_plan()
        meta = parse_meta()
        build_documents(plan)
        WIKI_DIR.mkdir(exist_ok=True)
        INDEX_PATH.write_text(render_index(plan, meta))
        print(f"Wrote {INDEX_PATH}")
    except PlanError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
